FROM r-base:3.6.1
# Install system dependencies for popcycle R package installation
# Separating this image from the image that installs popcycle + deps allows for
# smaller pulls after reinstalling new popcycle versions.

ARG MAKE_JOBS=4

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libgit2-dev \
    libssh2-1-dev \
    libssl-dev \
    file \
    libxml2-dev \
    libgeos-dev \
    curl \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL -o /usr/local/bin/seaflowpy https://github.com/armbrustlab/seaflowpy/releases/latest/download/seaflowpy-linux64 \
    && chmod +x /usr/local/bin/seaflowpy

COPY DESCRIPTION install-deps-only.R NAMESPACE LICENSE /src/

WORKDIR /src/

# Allow parallel compilation
ENV MAKE make -j ${MAKE_JOBS}
RUN Rscript install-deps-only.R
